image: jtredoux/node-aws

stages:
  - deploy

master_deploy:
  stage: deploy
  only:
    - stage
  script:
    - echo "Building..."
    - npm install
    - npm run-script deploy
    - echo "Deloying master on AWS S3"
    - aws s3 rm s3://$AWS_BUCKET --recursive
    - aws s3 sync ./build/ s3://$AWS_BUCKET