#include "AIConstants.h"

char AI_MODEL[] = "AI_MODEL";
char ATTR_AGENTMODEL[] = "ATTR_AGENTMODEL";

StrId NET_MSG_AGENT_UPDATE("NET_MSG_AGENT_UPDATE");
StrId NET_MSG_AGENT_CREATED("NET_MSG_AGENT_CREATED");
StrId NET_MSG_AGENTS_SNAPSHOT("NET_MSG_AGENTS_SNAPSHOT");